
ANACONDA_ROOT=/home/softwares/local/anaconda3
PATH=$ANACONDA_ROOT/bin:$PATH
LD_LIBRARY_PATH=$ANACONDA_ROOT/lib:$LD_LIBRARY_PATH
MANPATH=$ANACONDA_ROOT/share/man/:$MANPATH
INFOPATH=$ANACONDA_ROOT/share/info:$INFOPATH
PKG_CONFIG_PATH=$ANACONDA_ROOT/lib/pkgconfig:$PKG_CONFIG_PATH

export ANACONDA_ROOT
export PATH
export LD_LIBRARY_PATH
export MANPATH
export INFOPATH
export PKG_CONFIG_PATH

